### ISSUE TITLE
Total Supply Calculation

### ISSUE THREAD

**Issue by tijno** [deso-protocol/docs#14]
@diamondhands0 you [asked me to check your calc](https://bitclout.com/posts/7bf4cfb5a9328c0f42c74454479ce4f889938157ae8208ae9d8120bf5b0f3ffc) and posted [WIP calc here](https://bitclout.com/posts/c90d8fce66443844b78ceda2f1478114d2433d13349bb19d0e47fa3741e11cdc).

![20210614-2FDOzuIG](https://user-images.githubusercontent.com/69529928/121954565-d20ed100-cd56-11eb-9728-ad8e2b69c360.png)

Very close but small variance that would be good to understand and remove.

Also I would like to do Bottom up sum of all balances to make sure that the total supply number exists somewhere on the blockchain.

This is where I am running into more trouble, as not all transactions have Outputs - which may be at my end of course.

**Comment by tijno** [comment]
Ah just realised - Transaction schema has changed after block 33527, so missing some data upto block 33828 due to this change:

https://github.com/bitclout/backend/commit/f7d0fa0dc67633f57c093d46bfaba3c01e55607c

**Comment by tijno** [comment]
Ok thats my issue resolved - with slightly smaller variance remaining.

Most likely due to block you calculated at and therefore slightly lower or higher mining reward. 

Let me know if you have any thoughts about how we can verify bottom up specifically.

* Unspend outputs, excl Bitcoin Purchases  (Balance of outputs that are not used as Input anywhere)
* Clout locked in Creator Coins (Purchases - Sales)
* Unused $clout from Bitcoin purchase

**Comment by tijno** [comment]
We are now almost 2 weeks in from dbomb - anything i can do to move this issue here foreward ? 

i think its really important the circulation can be reconciled with the blockchain at any time.

having issues like core #46 and this one outstanding can damage bitclout credibility.

lets get it sorted @diamondhands0 @maebeam

**Comment by diamondhands0** [comment]
My calculation was very simple:

- 2M founder coins
- 8,532,253.885390055 BitClout sold according to the [get-exchange-rate endpoint](https://github.com/bitclout/backend/blob/fd79bf07f3b22272ef99e9c798d89e7c3ca4be8b/routes/base.go#L49), which sums all BitcoinExchange txns
- 276,238.800000000 coins that will be mined in the long-term according to supply.go and verified in supply_test.go [here](https://github.com/bitclout/core/blob/cd41d24241be57034bc1ca245daf4b56fbd968b2/lib/supply_test.go#L34)

Sum this all up and you get a MAX supply in the long-term of: 2M+8,532,253.885390055+276,238.800000000 = 10,808,492.6854.

Your estimate looks like it comes within 1.29 $CLOUT of mine. It would be interesting to understand where that variance is coming from, but not urgent given that the numbers are fairly close. I'll leave it open for now in case someone wants to reconcile that last $CLOUT in the future.

Thanks for the hard work here @tijno. I was surprised to see I don't own any of your coin yet so just made my first purchase.

**Comment by tijno** [comment]
@diamondhands0 Most likely the variance is just due to a difference on time numbers were taken.

Agree not a huge priority.

What for me is more important is to be able to verify it bottom up as well.

This is not as easy especially as certain transactions are not clearly on chain as an output - eg like FR.

But this is where my lack of knowledge of exactly how certain things are counted and calculated holds me back. Going through core code to get better knowledge. 

I would love to make progress on that specifically.

ps thx for the investment :)

**Comment by diamondhands0** [comment]
Ah, I see. Yes, a bottom-up script would be very useful. I'll actually send you 5 $CLOUT if you can do it :)

I think the best way to do that is simply to sum up all the UTXOs in the db. I'm not sure if you've done much work with the badgerdb key-value store yet, but all of the UTXOs are indexed under the [_PrefixUtxoKeyToUtxoEntry](https://github.com/bitclout/core/blob/5ce03b9318b6b447f895cc9db7d61de54736c1a6/lib/db_utils.go#L67) index. It looks like you could write a script to go through that using [EnumerateKeysForPrefix](https://github.com/bitclout/core/blob/5ce03b9318b6b447f895cc9db7d61de54736c1a6/lib/db_utils.go#L373) that parses the UtxoEntrys and sums their amounts.

I think you can modify the run.go file to do this when the node starts up [here](https://github.com/bitclout/core/blob/5ce03b9318b6b447f895cc9db7d61de54736c1a6/cmd/run.go#L38) or deeper in the code [here](https://github.com/bitclout/core/blob/5ce03b9318b6b447f895cc9db7d61de54736c1a6/cmd/node.go#L152).

**Comment by tijno** [comment]
cool will look at it

tried to do it with json transaction data in all blocks which i have in BQ

but not everything is listed as an output although ive not checked the recent addition of TxOutputs.

**Comment by diamondhands0** [comment]
Hmm... I think it will be hard to do it that way because of "implicit" outputs generated by BitcoinExchange and CreatorCoin sell txns. These implicit outputs are not included in the txn, nor are they included in the TxOutputs in the JSON transaction data. I believe the Rosetta API has some hackey way of computing the implicit outputs that you could look at, but it's not ideal. If you could sum the UTXOs in the db after syncing, that seems like the simplest way and should get you a bullet-proof answer.

**Comment by znmead** [comment]
> Your estimate looks like it comes within 1.29 $CLOUT of mine. It would be interesting to understand where that variance is coming from, but not urgent given that the numbers are fairly close. I'll leave it open for now in case someone wants to reconcile that last $CLOUT in the future.

Chain dropped one for all the dead homies... I knew this chain was cool as hell. 

You guys are champs, thanks for all your hard work on this.

**Comment by tijno** [comment]
The sheet on deso.org helps but it does not line up 

Still dont have all the answers i was looking for - leaving this here for ref as outlined to @AeonSw4n  on discord.

I still think this should be clarified - but I cant really be bothered to spend the effort required to do so.

**1) sum of buys upto end feb - before genesis - is below 6m - its around 5.5m (from memory as im not at desk)**

Take sum of DESO Minted on this sheet (linked from deso.org homepage) upto but before 1 March: https://docs.google.com/spreadsheets/d/1eSlyJzP8kkLdoNmExDiKrIXKnjjDE3wCPAHvH4wNB4s/edit#gid=0

Just under 5.5m DESO.

But genesis block includes 8m - 2m of which is FR. But that leaves about 500k DESO unaccounted for.

In addition - take the first onchain Bitcoin transactions. 
https://explorer.deso.org/?query-node=https:%2F%2Fapi.bitclout.com&transaction-id=3JuETHCeu4u4sJ5yRRpY4RKu6JwUqYyN45PefrCuAqQ2NDs5P7D31v

It has "TotalNanosPurchasedBefore": 6000000000000000

This is not true as the sheet only identifies 5.5m

What is the source of this discrepancy? 
Does this mean all DESO minted on chain had inflated price due to additinal 500k?

**2) when i lookup the buys after genesis on chain - the nanos received for each buy vary between 25-35% from what is in the sheet for the exact same tx (using btc txid to find them). The variance is not consistent - so its not founder reward.**

Take first 1 March buy from this (deso.org) sheet: https://docs.google.com/spreadsheets/d/1eSlyJzP8kkLdoNmExDiKrIXKnjjDE3wCPAHvH4wNB4s/edit#gid=0

Row 396 - Mar 01 2021 - 06:41
BTC: 0.00078172
1.58849799 DESO Minted
BTC Transaction: e2fb373d257a2de3db0f657b2366a966fbabad3bcb445e45eeb36e12008d5d47

On chain DESO transaction: 3JuETHCeu4u4sJ5yRRpY4RKu6JwUqYyN45PefrCuAqQ2NDs5P7D31v
https://explorer.deso.org/?query-node=https:%2F%2Fapi.bitclout.com&transaction-id=3JuETHCeu4u4sJ5yRRpY4RKu6JwUqYyN45PefrCuAqQ2NDs5P7D31v
Sats "burned": 78172 (0.00078172)
Nanos created: 1161061795 (1.161061795)

So the DESO in the Sheet is 0.42 DESO higher then what is on chain.

I initially thought this may be due to FR - but the % difference between each transaction differ and are inconsistent. Eg 25-35% variance. Also post genesis bitcoin exchange does not give FR to founders.

**Comment by iPaulPro** [comment]
Yeah none of it lines up and it seems clear that they dgaf about what we think of it.

We don't even have consistent circulating supply numbers. It's different for each node that you check.
