### ISSUE TITLE
Clarification on subdomains.

### ISSUE THREAD

**Issue by tijno** [deso-protocol/docs#6]
When using a subdomain for my node, as [per the docs here](https://github.com/bitclout/docs/blob/main/running-a-node.md#example-dns-records), the front end makes requests to `api.node.domain.com` so A record needs to be set for that rather then `api.domain.com`.

**Comment by LvlUpGuy** [comment]
Great catch! Getting this resolved. Thank you!

**Comment by marshj1977** [comment]
Hmmm - related to https://github.com/bitclout/run/issues/28#issuecomment-840843275 ?
